name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: v1.x

      - name: Run Format
        run: deno fmt --check

      # - name: Run Lin
      #   run: deno lint

      - name: Run Tests
        run: deno test